import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ConfigProvider } from "antd";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ConfigProvider
          theme={{
            token: {
              colorPrimary: "#f5222d",
              colorInfo: "#f5222d",
              sizeStep: 6,
              borderRadius: 5,
              wireframe: false,
              fontSize: 17,
            },
            components: {
              Button: {
                contentFontSize: 14,
                contentFontSizeLG: 15,
                contentFontSizeSM: 0,
                contentLineHeightLG: 7.5,
                paddingBlock: 4,
                controlHeight: 49,
              },
              Input: {
                controlHeight: 48,
                lineWidth: 2,
                borderRadius: 15,
              },
              Layout: {
                headerHeight: 55,
                headerBg: "rgb(34,36,38)",
              },
              Spin: {
                dotSize: 57,
                fontSize: 25,
                motionDurationMid: "0.1s",
              },
              Carousel: {
                dotHeight: 12,
              },
            },
          }}
        >
          {children}
        </ConfigProvider>
      </body>
    </html>
  );
}
